dotVersionFiles:
  - atmo/release/version.go
  - docs/concepts/the-directive.md
  - docs/usage/creating-handlers.md

preMakeTargets:
  - build
  - test

postMakeTargets:
  - docker/publish version={{ .Version }}
  - docker/publish/latest